# Tresholds to treat detected stuff like if they were there
# Remember, NO indentation by tabs!!!
version: &software_version "v0.1.0-a"
logs:
    actions:	../logs/actions/actions.txt
    calculations:	../logs/actions/calculations.md

tresholds:
  # mean Average perception needed to recognise object
  mAP:
    candle: 				0.2
    line_border: 			0.3
    line_surround: 			0.3
    fire: 					0.6
    barrier: 				0.2
    person: 				0.8
    Maker_Jakub_Ramaseuski: 0.8


priority:
  exploration:
    # priorities of how much such place should be visited.
    candle: 		8192
    candle_blown: 	0
    unknown: 		128
    barrier:		300
    discovered: 	-64
    interesting: 	1024
    boring: 		-128
    
    #~ influence_unknown: 2       
    #influence dividor of other unknown fields    
    
    #~ influence_discovered: 2
    #influence of close location which is discovered
    
  influence:
    # influence of how such place in tiles.
    candle: 		6
    candle_blown: 	4
    unknown: 		4
    barrier:		8
    discovered: 	9
    interesting: 	7
    boring: 		18
    
    #~ influence_unknown: 2       
    #influence dividor of other unknown fields    
    
    #~ influence_discovered: 2
    #influence of close location which is discovered
properties:
  camera:
    angle_vertical: 				37
    angle_horizontal: 				66
    size_recognition_horizontal: 	192
    size_recognition_vertical: 		320
    size_footage_horizontal: 		360
    size_footage_vertical: 			640

  #~ robot:
    #~ wheel:
      #~ radius: 	0.044
      #~ steps: 	200
      
information: |
 Roborave robot software, version 0.1.0-a
 © Jakub Ramašeuski, 2021
