# Tresholds to treat detected stuff like if they were there
 
tresholds:
  mAP:
    candle: 0.2
    line_border: 0.3
    line_surround: 0.3
    fire: 0.6
    barrier: 0.2


priority:
  exploration:
    candle: 8192
    candle_blown: 0
    unknown: 128
    barrier: 300
    discovered: -64
    interesting: 1024
    boring: -128
    
    influence_unknown: 2       
    #influence dividor of other unknown fields    
    
    influence_discovered:     2
    #influence of close location which is discovered
